export const TOPICS = [
  "React-Router",
  "Jest",
  "React-Testing-Library",
  "ShimmerUI",
  "Cart",
  "Countdown-Timer",
  "MultiLanguageSupport",
  "Infinite-Scroll",
  "Accordian",
  "Redit Nested Components",
  "Image Slider",
  "Real Time Updates",
  "You Tube Live Stream Chat",
  "AutoComplete and SearchBar",
  "Building YouTube",
  "Multi Select Component",
  "Text Editor",
  "Responsive Navigation Bar",
  "Analog Clock",
  "Whats app Chat",
  "Snake Game",
  "Tic Tac Toe",
  "Connect Four",
  "Modal Component",
  "Dropdown Menu",
  "Simple Calculator",
  "Drag and Drop List",
  "Image Upload and Preview",
];

export const GIFS_TRENDING_API = `https://api.giphy.com/v1/gifs/trending?api_key=${process.env.REACT_APP_GIF_TRENDING_API_KEY}&limit=25&offset=0&rating=g&bundle=messaging_non_clips`;

export const languages = [
  { type: "en", content: "Write anything", lang: "English" },
  { type: "hi", content: "कुछ भी लिखो", lang: "Hindi" },
  { type: "sp", content: "escribe cualquier cosa", lang: "Spanish" },
  { type: "ch", content: "写任何东西", lang: "Chinese" },
  { type: "ja", content: "何でも書いてください" , lang: "Japenese"},
];
