export const TOPICS = [
  "React-Router",
  "Jest",
  "React-Testing-Library",
  "ShimmerUI",
  "Context API",
  "Countdown Timer (Redux Toolkit)",
  "Multi Language Support",
  "Infinite Scroll",
  "Accordian",
  "Redit Nested Components",
  "Image Slider",
  "Real Time Updates",
  "You Tube Live Stream Chat",
  "AutoComplete and SearchBar",
  "Building YouTube",
  "Multi Select Component",
  "Text Editor",
  "Responsive Navigation Bar",
  "Analog Clock",
  "Whats app Chat",
  "Snake Game", 
  "Tic Tac Toe", 
  "Connect Four",
  "Modal Component",
  "Dropdown Menu",
  "Simple Calculator",
  "Drag and Drop List",
  "Image Upload and Preview",
];
